### ISSUE TITLE
Help! it crashes I love your mod By the way

### ISSUE THREAD

**Issue by FETHERTHEFISH** [pWn3d1337/Techguns#126]
I need help 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  weaponlib (mw-1.11.6_mc1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-50.jar)
  TANLoadingPlugin (ToughAsNails-1.x.x-4.0.0.null-universal.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 1/24/18 3:55 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NoClassDefFoundError: toughasnails/particle/EntitySnowflakeFX
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:583)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: toughasnails.particle.EntitySnowflakeFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: glitchcore/particle/GFParticle
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: glitchcore.particle.GFParticle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1742269528 bytes (1661 MB) / 2330460160 bytes (2222 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 4 total; -Xmx10240m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2581 111 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                | Source                                          | Signature                                |
	|:----- |:------------------------ |:---------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                | 1.12.2                 | minecraft.jar                                   | None                                     |
	| UC    | mcp                      | 9.42                   | minecraft.jar                                   | None                                     |
	| UC    | FML                      | 8.0.99.99              | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                    | 14.23.1.2581           | forge-1.12.2-14.23.1.2581.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | advancedrocketrycore     | 1                      | minecraft.jar                                   | None                                     |
	| UC    | techguns_core            | 1.12.2-1.0             | minecraft.jar                                   | None                                     |
	| UC    | actuallyadditions        | 1.12.2-r128            | ActuallyAdditions-1.12.2-r128.jar               | None                                     |
	| UC    | redstoneflux             | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | cofhcore                 | 4.3.10                 | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UC    | libvulpes                | 0.2.7.-25              | LibVulpes-1.12.2-0.2.7-25-universal.jar         | None                                     |
	| UC    | advancedrocketry         | 1.2.6.-50              | AdvancedRocketry-1.12.2-1.2.6-50.jar            | None                                     |
	| UC    | appliedenergistics2      | rv5-stable-5           | appliedenergistics2-rv5-stable-5.jar            | None                                     |
	| UC    | crafttweaker             | 4.1.0                  | CraftTweaker2-1.12-4.1.0.jar                    | None                                     |
	| UC    | astralsorcery            | 1.8.4                  | astralsorcery-1.12.2-1.8.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UC    | baubles                  | 1.5.2                  | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UC    | bdlib                    | 1.14.3.12              | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| UC    | biomesoplenty            | 7.0.1.2313             | BiomesOPlenty-1.12.2-7.0.1.2313-universal.jar   | None                                     |
	| UC    | bookshelf                | 2.3.523                | Bookshelf-1.12.2-2.3.523.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | buildcraftlib            | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftcore           | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftbuilders       | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftenergy         | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftfactory        | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftrobotics       | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcraftsilicon        | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | buildcrafttransport      | 7.99.14                | buildcraft-7.99.14.jar                          | None                                     |
	| UC    | ic2                      | 2.8.42-ex112           | industrialcraft-2-2.8.42-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | mekanism                 | 1.12.2-9.4.3.330       | Mekanism-1.12.2-9.4.3.330.jar                   | None                                     |
	| UC    | sonarcore                | 5.0.4                  | sonarcore-1.12.2-5.0.4.jar                      | None                                     |
	| UC    | calculator               | 5.0.2                  | calculator-1.12.2-5.0.2.jar                     | None                                     |
	| UC    | chisel                   | MC1.12-0.1.1.26        | Chisel-MC1.12-0.1.1.26.jar                      | None                                     |
	| UC    | classiccombat            | 1.0.0                  | ClassicCombat-1.12-1.0.0.jar                    | None                                     |
	| UC    | codechickenlib           | 3.1.5.331              | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | cofhworld                | 1.1.1                  | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UC    | cyclopscore              | 0.11.1                 | CyclopsCore-1.12.2-0.11.1.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | commoncapabilities       | 1.4.0                  | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UC    | ctgui                    | 1.0.0                  | CraftTweaker2-1.12-4.1.0.jar                    | None                                     |
	| UC    | crafttweakerjei          | 2.0.0                  | CraftTweaker2-1.12-4.1.0.jar                    | None                                     |
	| UC    | crossroads               | 1.12-1.6.5             | crossroads-1.12-1.6.5.jar                       | None                                     |
	| UC    | darkutils                | 1.8.192                | DarkUtils-1.12.2-1.8.192.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | ptrmodellib              | 1.0.0                  | Decocraft-2.5.2_1.12.2.jar                      | None                                     |
	| UC    | props                    | 2.5.2                  | Decocraft-2.5.2_1.12.2.jar                      | None                                     |
	| UC    | eleccore                 | 1.8.434                | ElecCore-1.12.2-1.8.434.jar                     | None                                     |
	| UC    | elementaldimensions      | 0.2.0                  | elementaldimensions-1.12-0.2.0.jar              | None                                     |
	| UC    | valkyrielib              | 1.12.2-2.0.6b          | valkyrielib-1.12.2-2.0.6b.jar                   | None                                     |
	| UC    | environmentaltech        | 1.12.2-2.0.6b          | environmentaltech-1.12.2-2.0.6b.jar             | None                                     |
	| UC    | everlastingabilities     | 1.3.9                  | EverlastingAbilities-1.12.2-1.3.9.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | evilcraft                | 0.10.45                | EvilCraft-1.12.2-0.10.45.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | evilcraftcompat          | 1.0.0                  | EvilCraft-1.12.2-0.10.45.jar                    | None                                     |
	| UC    | mantle                   | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UC    | tconstruct               | 1.12.2-2.9.0.55        | TConstruct-1.12.2-2.9.0.55.jar                  | None                                     |
	| UC    | extrautils2              | 1.0                    | extrautils2-1.12-1.7.2.jar                      | None                                     |
	| UC    | fluxnetworks             | 3.0.2                  | fluxnetworks-1.12.2-3.0.2.jar                   | None                                     |
	| UC    | foodexpansion            | 1.3                    | FoodExpansion1.3.2-1.12.jar                     | None                                     |
	| UC    | thermalfoundation        | 2.3.10                 | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UC    | advgenerators            | 0.9.20.12              | generators-0.9.20.12-mc1.12.2.jar               | None                                     |
	| UC    | gravestone               | 1.0.13                 | GraveStone-1.12-Graves-1.0.13.jar               | None                                     |
	| UC    | gravestone-extended      | 1.3.0b2                | GraveStone-1.12.2-Extended-1.3.0b2.jar          | None                                     |
	| UC    | immcraft                 | 1.4.0                  | immcraft-1.12-1.4.0.jar                         | None                                     |
	| UC    | immersiveengineering     | 0.12-76                | ImmersiveEngineering-0.12-76.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UC    | immersivepetroleum       | @VERSION@              | immersivepetroleum-1.12.2-1.1.6.jar             | None                                     |
	| UC    | industrialwires          | 1.6-24                 | IndustrialWires-1.6-24.jar                      | 7e11c175d1e24007afec7498a1616bef0000027d |
	| UC    | integrateddynamics       | 0.10.2                 | IntegratedDynamics-1.12.2-0.10.2.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | integrateddynamicscompat | 1.0.0                  | IntegratedDynamics-1.12.2-0.10.2.jar            | None                                     |
	| UC    | integratedtunnels        | 1.4.1                  | IntegratedTunnels-1.12.2-1.4.1.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | integratedtunnelscompat  | 1.0.0                  | IntegratedTunnels-1.12.2-1.4.1.jar              | None                                     |
	| UC    | journeymap               | 1.12.2-5.6.0b2         | journeymap-1.12.2-5.6.0b2.jar                   | None                                     |
	| UC    | lycanitesmobs            | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | arcticmobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | demonmobs                | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | desertmobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | elementalmobs            | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | forestmobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | freshwatermobs           | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | infernomobs              | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | junglemobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | mountainmobs             | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | plainsmobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | saltwatermobs            | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | shadowmobs               | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | swampmobs                | 1.17.7.0 - MC 1.12.2   | LycanitesMobsComplete+1.17.7.0+[1.12.2].jar     | None                                     |
	| UC    | mekanismgenerators       | 9.4.3                  | MekanismGenerators-1.12.2-9.4.3.330.jar         | None                                     |
	| UC    | mekanismtools            | 9.4.3                  | MekanismTools-1.12.2-9.4.3.330.jar              | None                                     |
	| UC    | mw                       | 1.11.6                 | mw-1.11.6_mc1.12.2.jar                          | None                                     |
	| UC    | nuclearcraft             | 2.9                    | NuclearCraft-2.9--1.12.2.jar                    | None                                     |
	| UC    | thermalexpansion         | 5.3.10                 | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UC    | omlib                    | 3.0.0-133              | omlib-1.12.2-3.0.0-133.jar                      | None                                     |
	| UC    | openmodularturrets       | 3.0.0-230              | openmodularturrets-1.12.2-3.0.0-230.jar         | None                                     |
	| UC    | harvestcraft             | 1.12.2m                | Pam's+HarvestCraft+1.12.2m.jar                  | None                                     |
	| UC    | projecte                 | 1.12-PE1.0.0           | ProjectE-1.12-PE1.2.0.jar                       | None                                     |
	| UC    | plustic                  | 6.3.2.1                | plustic-6.3.2.1.jar                             | None                                     |
	| UC    | rangedpumps              | 0.5                    | rangedpumps-0.5.jar                             | None                                     |
	| UC    | realistictorches         | 2.1.1                  | RealisticTorches-1.12.2-2.1.1.jar               | None                                     |
	| UC    | reborncore               | 3.6.4.194              | RebornCore-1.12.2-3.6.4.194-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | rftools                  | 7.23                   | rftools-1.12-7.23.jar                           | None                                     |
	| UC    | roots                    | 0.104                  | roots-2-0.104.jar                               | None                                     |
	| UC    | shetiphiancore           | 3.5.6                  | shetiphiancore-1.12.0-3.5.6.jar                 | None                                     |
	| UC    | stevescarts              | ${version}             | StevesCarts-1.12.2-2.4.16.81.jar                | None                                     |
	| UC    | techguns                 | 2.0.1.1                | techguns-1.12.2-2.0.1.1.jar                     | None                                     |
	| UC    | techreborn               | 2.12.1.446             | TechReborn-1.12.2-2.12.1.446-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | terraqueous              | 1.4.8                  | terraqueous-1.12.0-1.4.8.jar                    | None                                     |
	| UC    | thermaldynamics          | 2.3.10                 | ThermalDynamics-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UC    | tinker_io                | release 2.5.6e         | tinker_io-1.12-release+2.5.6e.jar               | None                                     |
	| UC    | tinkersaddons            | 1.0.7                  | Tinkers'+Addons-1.12.1-1.0.7.jar                | None                                     |
	| UC    | tinkersdefense           | 1.4.2.4a               | tinkersdefense-1.4.2.4a.jar                     | None                                     |
	| UC    | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UC    | toroquest                | 1.12.2-5.2             | toroquest-1.12.2-5.2.jar                        | None                                     |
	| UE    | toughasnails             | 4.0.0                  | ToughAsNails-1.x.x-4.0.0.null-universal.jar     | None                                     |
	| UC    | ultimate_unicorn_mod     | 1.5.14                 | ultimate_unicorn_mod-1.12.2-1.5.14.jar          | None                                     |
	| UC    | wanionlib                | 1.12.2-1.4             | WanionLib-1.12.2-1.4.jar                        | None                                     |
	| UC    | unidict                  | 1.12.2-2.3.1           | UniDict-1.12.2-2.3.1.jar                        | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
weaponlib (mw-1.11.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-50.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.x.x-4.0.0.null-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
	AE2 Version: stable rv5-stable-5 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

**Comment by pWn3d1337** [comment]
This crash is not caused by techguns.

"toughasnails" is causing it.
