### ISSUE TITLE
Crash when using Voidaic Arcana

### ISSUE THREAD

**Issue by FluffyyRayne** [pWn3d1337/Techguns#205]
Not sure which mod git to post it to so I'm posting it in both. Game crashes when entering the void dimension from Voidaic Arcana. No other mods used besides necessary ones for TG and VA to work.
Tested on Forge 2705, 2710 and 2770.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/13/18 8:03 PM
Description: Exception ticking world

java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:246)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:127)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:246)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:127)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Rayd3rX'/2198, l='New World', x=1391.50, y=250.00, z=1499.50]]
	Chunk stats: ServerChunkCache: 42 Drop: 0
	Level seed: 4677720909670575523
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 650713080 bytes (620 MB) / 1090519040 bytes (1040 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version           | Source                               | Signature                                |
	|:--------- |:-------------- |:----------------- |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2            | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp            | 9.42              | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99         | forge-1.12.2-14.23.5.2770.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge          | 14.23.5.2770      | forge-1.12.2-14.23.5.2770.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | techguns_core  | 1.12.2-1.0        | minecraft.jar                        | None                                     |
	| UCHIJAAAA | baubles        | 1.5.2             | Baubles-1.12-1.5.2.jar               | None                                     |
	| UCHIJAAAA | ctm            | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar            | None                                     |
	| UCHIJAAAA | chisel         | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar         | None                                     |
	| UCHIJAAAA | techguns       | 2.0.1.1           | techguns-1.12.2-2.0.1.1.jar          | None                                     |
	| UCHIJAAAA | voidaicarcania | 0.4               | Voidaic+Arcania+v0.2.2b+mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Rayd3rX'/2198, l='New World', x=1391.50, y=250.00, z=1499.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by pWn3d1337** [comment]
referenced in 1.12 issue tracker
