### ISSUE TITLE
vanilla fix says techguns ran into issues that may cause world corruption

### ISSUE THREAD

**Issue by superdumpling** [pWn3d1337/Techguns#237]
It started after I placed down several turrets, I went to the crash log and this is what came up
I tried removing the 3 simple machines I had in my base and it was still showing up. Any fix because I'd like to keep the turrets to get the rapidly spawning miners off my lawn

```
PDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=machinetype, clazz=class techguns.blocks.machines.EnumSimpleMachineType, values=[CAMO_BENCH, REPAIR_BENCH, CHARGING_STATION]} as it does not exist in BlockStateContainer{block=techguns:basicmachine, properties=[machinetype]}
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=machinetype, clazz=class techguns.blocks.machines.EnumSimpleMachineType, values=[CAMO_BENCH, REPAIR_BENCH, CHARGING_STATION]} as it does not exist in BlockStateContainer{block=techguns:basicmachine, properties=[machinetype]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at techguns.tileentities.BasicInventoryTileEnt.shouldRefresh(BasicInventoryTileEnt.java:133)
    at net.minecraft.world.chunk.Chunk.read(Chunk.java:1201)
    at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:745)
    at net.minecraft.network.play.server.SPacketChunkData.processPacket(SourceFile:96)
    at net.minecraft.network.play.server.SPacketChunkData.processPacket(SourceFile:18)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
```

**Comment by Sereath** [comment]
Here to report the same:

https://gist.github.com/Sereath/687428db6de3b788fda109da2a5affa4
