### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by BlueYoshi68** [pWn3d1337/Techguns#258]
Not sure why im bothering to type this, but tech guns is crashing for no reason.
`java.lang.ArrayIndexOutOfBoundsException: 5
    at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
    at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
    at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
    at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:34)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:412)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:392)
    at net.minecraft.client.renderer.RenderGlobal.redirect$zcj000$renderEntityStatic(RenderGlobal.java:3727)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:839)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1800)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by pWn3d1337** [comment]
I think this crash is caused by optifine
