### ISSUE TITLE
Server Frequently Segfaults when Techguns Present

### ISSUE THREAD

**Issue by xenoswift** [pWn3d1337/Techguns#36]
Been having a lot of issues keeping a pack+server stable when using Techguns. I had segfaults on world load at a point, but removing Techguns has alleviated the problem. 

I can give you a heap of crash reports. The hs_err logs I got were completely useless in helping me find the issue, as I just got a hunch since Techguns is the most alpha/beta-state mod in the pack.

https://www.dropbox.com/s/j6qxqtdyy1zsw4l/crash-reports.zip?dl=1

If there's something I can do to get the mod to be at least stable -- providing modlist, minetweaker scripts, hardware specs -- I'd love to offer anything I can. 

But I can definitely ask that you make it open source so other people can help contribute to the mod and try to make it better. You have a real gem here, I'm really hesitant to remove it because it adds a unique flavour to the world.

**Comment by pWn3d1337** [comment]
Only 3 reports where directly related to techguns. It was 3 times the same error. But I have not seen this before, I will look into this.

**Comment by asiekierka** [comment]
I am pretty sure (though not 100% sure) it's not Techguns's fault.

**Comment by pWn3d1337** [comment]
The error for the techguns related crashes is caused by IO related to NBT tags.

```
java.io.UTFDataFormatException: malformed input around byte 0
	at java.io.DataInputStream.readUTF(DataInputStream.java:656)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at net.minecraft.nbt.NBTTagCompound.func_152448_b(NBTTagCompound.java:388)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:50)
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at techguns.util.BlockUtils.selectEntitiesWithinAABB(BlockUtils.java:721)
	at techguns.tileentities.CampFlagTileEnt.countNPCs(CampFlagTileEnt.java:112)
	at techguns.tileentities.CampFlagTileEnt.func_145845_h(CampFlagTileEnt.java:75)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Seems like your PC has problems.

**Comment by xenoswift** [comment]
Seems to segfault with or without Techguns, across hardware.
