### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive 

### ISSUE THREAD

**Issue by jangofett890** [pWn3d1337/Techguns#75]
Tested alpha test 4 and last stable build 1.2 crashes when attempting to generate a flag for a base.

> [B#349]  [20:33:21] [Server thread/ERROR]: Encountered an unexpected exception
[B#349]  net.minecraft.util.ReportedException: Ticking block entity
[B#349]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#349]  Caused by: java.lang.IllegalArgumentException: bound must be positive
[B#349]  	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_131]
[B#349]  	at techguns.tileentities.CampFlagTileEnt.func_145845_h(CampFlagTileEnt.java:97) ~[CampFlagTileEnt.class:?]
[B#349]  	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
[B#349]  	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
[B#349]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
[B#349]  	... 4 more
[B#349]  [20:33:22] [Server thread/ERROR]: This crash report has been saved to: C:\Users\jango\AppData\Roaming\.technic\modpacks\neons-alientek\crash-reports\crash-2017-06-04_20.33.21-server.txt
[B#349]  [20:33:22] [Server thread/INFO]: Stopping server
[B#349]  [20:33:22] [Server thread/INFO]: Saving players
[B#349]  [20:33:22] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[B#349]  // Would you like a cupcake?
[B#349]  
[B#349]  Time: 6/4/17 8:33 PM
[B#349]  Description: Ticking block entity
[B#349]  
[B#349]  java.lang.IllegalArgumentException: bound must be positive
[B#349]  	at java.util.Random.nextInt(Unknown Source)
[B#349]  	at techguns.tileentities.CampFlagTileEnt.func_145845_h(CampFlagTileEnt.java:97)
[B#349]  	at net.minecraft.world.World.func_72939_s(World.java:1939)
[B#349]  	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[B#349]  	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[B#349]  	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#349]  	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[B#349]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#349]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[B#349]  
[B#349]  
[B#349]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#349]  ---------------------------------------------------------------------------------------
[B#349]  
[B#349]  -- Head --
[B#349]  Stacktrace:
[B#349]  	at java.util.Random.nextInt(Unknown Source)
[B#349]  	at techguns.tileentities.CampFlagTileEnt.func_145845_h(CampFlagTileEnt.java:97)
[B#349]  
[B#349]  -- Block entity being ticked --
[B#349]  Details:
[B#349]  	Name: CampFlagTileEnt // techguns.tileentities.CampFlagTileEnt
[B#349]  	Block type: ID #1059 (tile.BasicMachine // techguns.blocks.machines.BasicMachine)
[B#349]  	Block data value: 7 / 0x7 / 0b0111
[B#349]  	Block location: World: (-248,82,1032), Chunk: (at 8,5,8 in -16,64; contains blocks -256,0,1024 to -241,255,1039), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
[B#349]  	Actual block type: ID #1059 (tile.BasicMachine // techguns.blocks.machines.BasicMachine)
[B#349]  	Actual block data value: 7 / 0x7 / 0b0111
[B#349]  Stacktrace:
[B#349]  	at net.minecraft.world.World.func_72939_s(World.java:1939)
[B#349]  	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by pWn3d1337** [comment]
The flag should not be placed by hand, and is also not available in creative menu. You should not have the flag as item.

**Comment by jangofett890** [comment]
I'm not placing the flag, the game generated the base. I can upload a copy of the save if that would help. Getting near the base crashes the game.

**Comment by pWn3d1337** [comment]
ok, this is a bug then. I thought I fixed this already. I will look into it. No I don't need a save, the stack trace should be enough.

**Comment by jangofett890** [comment]
I was considering looking at the code myself and doing a fork when I posted this but you have no source code attached. Using the absolute value function before putting a value into the random(?) function should fix it I believe.

**Comment by pWn3d1337** [comment]
The problem is the flag wants to roll which spawnpoint to spawn, but it has no spawnpoints, so it calls random with 0 upper bound, which is not valid.

Under rare circumstances it seems to happen that a base generates without spawnpoints. I will add a safeguard to not roll a spawn if it has no spawns.

I will upload a fix soon.

**Comment by pWn3d1337** [comment]
Fix is up, should be approved soon.
