### ISSUE TITLE
java.lang.IndexOutOfBoundsException: 18496 at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253) at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)

### ISSUE THREAD

**Issue by COmmanderDerp999** [pWn3d1337/Techguns#86]
Tried your suggestion.  Says shutting down internal server

**Comment by pWn3d1337** [comment]
I thinkt thats the bug when you play MC with a version newer than 1.7 and set the render distance to something higher than 1.7 allows. Has nothing to do with techguns.
