### ISSUE TITLE
Client crash when trying to use Fabricator

### ISSUE THREAD

**Issue by LemADEC** [pWn3d1337/Techguns#89]
As of Techguns.beta.1.2_alphatest4.1, trying to open fabricator from side crashes client with an exception on server side.

Server side exception:
```
java.lang.NullPointerException
>       at net.minecraft.inventory.Slot.func_75211_c(Slot.java:67) ~[aay.class:?]
>       at net.minecraft.inventory.Container.func_75138_a(Container.java:120) ~[zs.class:?]
>       at net.minecraft.inventory.Container.func_75132_a(Container.java:109) ~[zs.class:?]
>       at techguns.inventory.FabricatorContainer.func_75132_a(FabricatorContainer.java:56) ~[FabricatorContainer.class:?]
>       at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:123) ~[FMLNetworkHandler.class:1.7.10-1614.57]
>       at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2437) ~[yz.class:?]
>       at techguns.blocks.machines.MultiBlockMachineBlock.func_149727_a(MultiBlockMachineBlock.java:324) ~[MultiBlockMachineBlock.class:?]
>       at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:465) ~[mx.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861) ~[nh.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
>       at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

Client side crash:
```
Time: 17/07/17 23:10
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at techguns.gui.GuiFabricator.func_146976_a(GuiFabricator.java:51)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at techguns.gui.GuiFabricator.func_146976_a(GuiFabricator.java:51)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: techguns.gui.GuiFabricator
	Mouse location: Scaled: (357, 174). Absolute: (715, 349)
	Screen size: Scaled: (715, 349). Absolute: (1430, 698). Scale factor of 2
```

**Comment by LemADEC** [comment]
Block was apparently corrupted, replacing it in creative fixed it.
